# Generated by Django 3.2 on 2021-05-03 10:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscription', models.DateField(default=datetime.date(2021, 5, 17))),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('TXT', 'Text'), ('AUDIO', 'Audio')], default='TXT', max_length=50)),
                ('genre', models.CharField(choices=[('COMEDY', 'Comedy'), ('TRAGEDY', 'Tragedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror')], default='DRAMA', max_length=50)),
                ('about', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(blank=True, through='subscriptions.AuthorBook', to='subscriptions.Author')),
            ],
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.book'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, through='subscriptions.AuthorBook', to='subscriptions.Book'),
        ),
    ]
